### ISSUE TITLE
TFM Devs

### ISSUE THREAD

**Issue by Scuph** [Scuph/ScuphUtilities#1]
I made this plugin to be added for TF, it's sort of like an info wise plugin, but adds a few features as well :)

@Wild1145 @JeromSar @WickedGamingUK @markbyrn

**Comment by JeromSar** [comment]
@Scuph We're not going to be adding any other plugins to TF for the time being, sorry! If you wish to contribute to development on TF, make PRs for TFM. :)

**Comment by Scuph** [comment]
Okay @JeromSar
